# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Board import Ui_BoardPage


class Ui_LoginPage(object):
    def buttonLoginClicked(self):
        LoginPage.hide()
        self.openBoard()

    def openBoard(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_BoardPage()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(722, 545)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginPage.setWindowIcon(icon)
        self.label_2 = QtWidgets.QLabel(LoginPage)
        self.label_2.setGeometry(QtCore.QRect(250, 160, 221, 51))
        font = QtGui.QFont()
        font.setFamily("TH Sarabun New")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LoginPage)
        self.label_3.setGeometry(QtCore.QRect(250, 260, 221, 51))
        font = QtGui.QFont()
        font.setFamily("TH Sarabun New")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtUsername = QtWidgets.QLineEdit(LoginPage)
        self.txtUsername.setGeometry(QtCore.QRect(250, 200, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Anantason Non Commercial Use")
        font.setPointSize(12)
        self.txtUsername.setFont(font)
        self.txtUsername.setStyleSheet("")
        self.txtUsername.setObjectName("txtUsername")
        self.txtPassword = QtWidgets.QLineEdit(LoginPage)
        self.txtPassword.setGeometry(QtCore.QRect(250, 300, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Anantason Non Commercial Use")
        font.setPointSize(12)
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.frame = QtWidgets.QFrame(LoginPage)
        self.frame.setGeometry(QtCore.QRect(200, 140, 321, 231))
        self.frame.setStyleSheet("border: 1px solid gray;\n"
                                 "    border-radius: 9px;\n"
                                 "background-color: #A69F97;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(LoginPage)
        self.frame_2.setGeometry(QtCore.QRect(0, -20, 751, 581))
        self.frame_2.setStyleSheet("background-color:#F2ECE9;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnLogIn = QtWidgets.QPushButton(self.frame_2)
        self.btnLogIn.setGeometry(QtCore.QRect(310, 420, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Anantason")
        font.setPointSize(12)
        self.btnLogIn.setFont(font)
        self.btnLogIn.setStyleSheet("border: 2.5px #BFB7A8;\n"
                                    "    border-radius: 9px;\n"
                                    "background-color:#BFB7A8;")
        self.btnLogIn.setObjectName("btnLogIn")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(270, 500, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Anantason Non Commercial Use")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(290, 80, 141, 61))
        font = QtGui.QFont()
        font.setFamily("TH Sarabun New")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2.raise_()
        self.frame.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.txtUsername.raise_()
        self.txtPassword.raise_()
        self.btnLogIn.clicked.connect(self.buttonLoginClicked)
        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "WorkBox"))
        self.label_2.setText(_translate("LoginPage", "Username"))
        self.label_3.setText(_translate("LoginPage", "Password"))
        self.btnLogIn.setText(_translate("LoginPage", "Log in"))
        self.label_4.setText(_translate("LoginPage", "ลืมรหัสผ่าน? กรุณาติดต่อผู้ดูแล"))
        self.label.setText(_translate("LoginPage", "เข้าสู่ระบบ"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QDialog()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
